[general]
context=from-sip
allowguest=no
allowoverlap=no
bindport=5060
bindaddr=0.0.0.0

[sip-provider]
type=peer
host=${SIP_PROVIDER_HOST}
fromdomain=${SIP_PROVIDER_HOST}
fromuser=${SIP_PROVIDER_USERNAME}
secret=${SIP_PROVIDER_PASSWORD}
qualify=yes
insecure=invite
nat=yes
canreinvite=no
context=outgoing